import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";
import Logotype from "@/components/ui/logotype/logotype";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <Link href="/">
            <Logotype />
          </Link>
          <ul>
            <li>
              <Link href="/">Dashboard</Link>
            </li>
            <li>
              <Link href="/films">films</Link>
            </li>
            <li>
              <Link href="/people">people</Link>
            </li>
            <li>
              <Link href="/planets">planets</Link>
            </li>
            <li>
              <Link href="/starships">starships</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
