import Logotype from '@/components/logotype/logotype';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ReactNode } from 'react';

import { Fraunces, Nunito_Sans } from 'next/font/google';
const fraunces = Fraunces({
  subsets: ['latin'],
  display: 'swap',
});
const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  display: 'swap',
});

import '../styles/index.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${fraunces.className} ${nunitoSans.className}`}>
      <body>
        <nav>
          <Link href="/">
            <Logotype />
          </Link>
          <ul>
            <li>
              <Link href="/">Dashboard</Link>
            </li>
            <li>
              <Link href="/films">films</Link>
            </li>
            <li>
              <Link href="/people">people</Link>
            </li>
            <li>
              <Link href="/planets">planets</Link>
            </li>
            <li>
              <Link href="/starships">starships</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
